### ISSUE TITLE
Reauth In realms menu

### ISSUE THREAD

**Issue by Giggles22031** [Basicprogrammer10/auto-reauth#3]
Not necessarily an issue, but I was just curious if it's at all possible to get it to reauth in the Realms menu too? I play a lot on Realms at the moment, and although it doesn't take long to just go over to the multiplayer menu, it would be a little more convenient for us realms users.

**Comment by Basicprogrammer10** [comment]
Good idea, I don't play realms so that didn't even cross my mind. Sorry for the late reply, for some reason I didn't get any notification or anything.

**Comment by Basicprogrammer10** [comment]
I made a new release that adds support for Realms.

- [Github Release](https://github.com/Basicprogrammer10/auto-reauth/releases/tag/v0.2.0-1.20.4)
- [Modrinth Release](https://modrinth.com/mod/auto-reauth/version/oXOsPeWR)
